// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcfkhkcwyemyvajrhnbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZmtoa2N3eWVteXZhanJobmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjc5NzksImV4cCI6MjA1ODk0Mzk3OX0.Zu8nuDroZLWDGxmSdDCCorRp2qknzAecLiBCOdirkro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);